name: shannon
channels:
- bioconda
- r
- defaults
- conda-forge
dependencies:
- htslib=1.3.2=0
- python-dateutil=2.6.0=py35_0
- curl=7.52.1=0
- mkl=2017.0.1=0
- numexpr=2.6.2=np112py35_0
- numpy=1.12.0=py35_0
- openssl=1.0.2k=1
- pandas=0.19.2=np112py35_1
- pip=9.0.1=py35_1
- python=3.5.1=5
- pytz=2016.10=py35_0
- readline=6.2=2
- setuptools=27.2.0=py35_0
- six=1.10.0=py35_0
- sqlite=3.13.0=0
- tk=8.5.18=0
- wheel=0.29.0=py35_0
- xz=5.2.2=1
- zlib=1.2.8=3

